### ISSUE TITLE
It goes behind navigation bar

### ISSUE THREAD

**Issue by Elamuruga** [HongliYu/DPDraggableButton-Swift#5]
while drag to up it goes behind the navigation bar and status bar so we can't able to access that it seems to be likened to hidden. Could you please help me with this?

**Comment by HongliYu** [comment]
I add a hot fix solution fro you, check the develop branch. Change the property named `upperBoundsDistance` to the height of navigation bar, then the component won't go up to that area

**Comment by Elamuruga** [comment]
> I add a hot fix solution fro you, check the develop branch. Change the property named `upperBoundsDistance` to the height of navigation bar, then the component won't go up to that area

@HongliYu Really thank you for your immediate response and fix for my issue. Its working fine. Could you please merge it?

**Comment by Elamuruga** [comment]
@HongliYu one more thing I need could you please reduce the deployment target to **iOS 10.0?** Thanks in advance include the change of the above issue. I need both the thing. Could you please help me with this?
